backend:
  name: github
  repo: umedard/gatsby_1
media_folder: static/assets
public_folder: assets
collections:
  - name: news
    label: News
    folder: content/news
    create: true
    fields:
      - { name: language, widget: "select", multiple: false, options: ["zh", "en"]}
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: "layout",label: "Layout", widget: "hidden", default: "news"}
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { name: category, widget: "select", multiple: false, options: ["Bulk Molding Compounds", "EMI Shielding Materials", "Inductive Components", "Polymer Adhesive Materials", "Thermal Management Materials"]}
      - { name: language, widget: "select", multiple: false, options: ["zh", "en"]}
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: "layout",label: "Layout", widget: "hidden", default: "products"}
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { name: language, widget: "select", multiple: false, options: ["zh", "en"]}
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: "layout",label: "Layout", widget: "hidden", default: "pages"}
  - name: contact
    label: Contact
    folder: content
    create: true
    fields:
      - { name: title, label: Title }
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Phone", name: "phone",  widget: "number", valueType: "int"}
      - {label: "Fax", name: "fax",  widget: "number", valueType: "int"}
      - { name: "layout",label: "Layout", widget: "hidden", default: "contact"}
  


     
    
    

    