backend:
  name: github
  repo: umedard/gatsby_1
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: language, widget: "select", multiple: false, options: ["zh", "en"]}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: "layout",label: "Layout", widget: "hidden", default: "blog"}
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { name: category, widget: "select", multiple: false, options: ["Bulk_Molding_Compounds", "EMI_Shielding_Materials", "Inductive_Components", "Polymer_Adhesive_Materials", "Thermal_Management_Materials"]}
      - { name: language, widget: "select", multiple: false, options: ["zh", "en"]}
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: "layout",label: "Layout", widget: "hidden", default: "products"}
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { name: language, widget: "select", multiple: false, options: ["zh", "en"]}
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - { name: "layout",label: "Layout", widget: "hidden", default: "pages"}


     
    
    
    
    